//Including the Express Module...
var express = require('express');
//creating an Instance of express...
var app = express();
//setting the port to listen to...
var port = 3000;
//Including cookie parser to parse the cookie...
var cookieParser = require('cookie-parser');
//including session...
var session = require('express-session');
//To setup logs...
var morgan = require('morgan');
//for database connectivity...
var mongoose = require('mongoose');
//to parse the data in address bar...
var bodyParser = require('body-parser');
//including passport module for using passport strategy...
var passport = require('passport');
//for showing flsh messages when there is any success or failure events occur...
var flash = require('connect-flash');

//including database connection file...
var configDB = require('./config/database.js');
//To connect to FacebookDB database...
mongoose.connect(configDB.url);
//including passport module from other file...
require('./config/passport')(passport);

//used to log all the api hits and status...
app.use(morgan('dev'));
app.use(cookieParser());
app.use(bodyParser.urlencoded({extended: false}));
//to setup cookies...
app.use(session({secret: 'mysecret',
				 saveUninitialized: true,
				 resave: true}));

app.use(passport.initialize()); //to initialize passport service...
app.use(passport.session()); // persistent login sessions...
app.use(flash()); // use connect-flash for flash messages stored in session...


app.set('view engine', 'ejs');


require('./app/routes.js')(app, passport);

app.listen(port);
console.log('Server running on port: ' + port);




